spring.application.name=auth-service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/driveDb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT CONFIG
jwt.secret=yourSuperSecretKeyForJwtAuthentication123456789
jwt.expiration=900000
jwt.refresh-expiration=604800000

#redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379
app.cookie.refresh-name=refresh_token